import { Post } from './post';

export const defaultPosts: Post[] = [
  {
    id: 1,
    userId: 101,
    title: 'Modern 2BR Apartment in Downtown',
    body: 'Newly renovated with hardwood floors, in-unit laundry, and skyline views.',
    price: 215000,
    location: 'Fargo, ND',
    imageUrl: 'https://placehold.co/400x200?text=Downtown+2BR',
    bedrooms: 2,
    bathrooms: 1,
    sqft: 950,
    verified: true,
    status: 'available',
    isRental: false,
  },
  {
    id: 2,
    userId: 102,
    title: 'Cozy 3BR Suburban Home',
    body: 'Family-friendly neighborhood, fenced backyard, and updated kitchen.',
    price: 279000,
    location: 'West Fargo, ND',
    imageUrl: 'https://placehold.co/400x200?text=Cozy+3BR+Home',
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1600,
    verified: true,
    status: 'available',
    isRental: false,
  },
  {
    id: 3,
    userId: 101,
    title: 'Luxury Lakefront Villa',
    body: '5BR, 4BA with a private dock, firepit, and home theater.',
    price: 739000,
    location: 'Detroit Lakes, MN',
    imageUrl: 'https://placehold.co/400x200?text=Lakefront+Villa',
    bedrooms: 5,
    bathrooms: 4,
    sqft: 4200,
    verified: true,
    status: 'sold',
    isRental: false,
  },
  {
    id: 4,
    userId: 103,
    title: 'Downtown Loft with Exposed Brick',
    body: 'Spacious loft-style unit with 15ft ceilings and panoramic windows.',
    price: 329000,
    location: 'Minneapolis, MN',
    imageUrl: 'https://placehold.co/400x200?text=Loft+Apartment',
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1400,
    verified: true,
    status: 'rented',
    isRental: false,
  },
  {
    id: 5,
    userId: 104,
    title: 'Affordable Starter Home',
    body: 'Perfect for first-time buyers, close to shopping and schools.',
    price: 189000,
    location: 'Dilworth, MN',
    imageUrl: 'https://placehold.co/400x200?text=Starter+Home',
    bedrooms: 2,
    bathrooms: 1,
    sqft: 1000,
    verified: true,
    status: 'available',
    isRental: false,
  },
  {
    id: 6,
    userId: 103,
    title: 'Spacious 4BR with Finished Basement',
    body: 'Includes fireplace, sunroom, and 2-car garage.',
    price: 359000,
    location: 'Mapleton, ND',
    imageUrl: 'https://placehold.co/400x200?text=Spacious+4BR',
    bedrooms: 4,
    bathrooms: 3,
    sqft: 2200,
    verified: true,
    status: 'available',
    isRental: false,
  },
  {
    id: 7,
    userId: 105,
    title: 'Pending Verification Condo',
    body: '2BR condo near university. Awaiting admin approval.',
    price: 199000,
    location: 'Fargo, ND',
    imageUrl: 'https://placehold.co/400x200?text=Pending+Verification',
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1100,
    verified: false,
    status: 'available',
    isRental: false,
  },
  {
    id: 8,
    userId: 106,
    title: 'Unverified Listing Test',
    body: 'This listing is for demo of unverified data. Should be hidden from public.',
    price: 145000,
    location: 'Valley City, ND',
    imageUrl: 'https://placehold.co/400x200?text=Hidden+Listing',
    bedrooms: 2,
    bathrooms: 1,
    sqft: 900,
    verified: false,
    status: 'available',
    isRental: false,
  },
  {
    id: 9,
    userId: 105,
    title: 'Fixer Upper Opportunity',
    body: 'Needs renovation. Great potential for investors.',
    price: 99000,
    location: 'Moorhead, MN',
    imageUrl: 'https://placehold.co/400x200?text=Fixer+Upper',
    bedrooms: 3,
    bathrooms: 1,
    sqft: 1400,
    verified: false,
    status: 'available',
    isRental: false,
  },
  {
    id: 10,
    userId: 106,
    title: 'New 1BR Downtown Apartment',
    body: 'Perfect for singles. Close to all amenities.',
    price: 1500,
    location: 'Fargo, ND',
    imageUrl: 'https://placehold.co/400x200?text=1BR+Downtown',
    bedrooms: 1,
    bathrooms: 1,
    sqft: 700,
    verified: true,
    status: 'available',
    isRental: true,
  },
  {
    id: 11,
    userId: 107,
    title: 'Shared 3BR Rental Unit',
    body: 'Shared housing with private bedrooms. Students welcome.',
    price: 500,
    location: 'Grand Forks, ND',
    imageUrl: 'https://placehold.co/400x200?text=Shared+3BR',
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1200,
    verified: true,
    status: 'rented',
    isRental: true,
  },
  {
    id: 12,
    userId: 108,
    title: 'Luxury Penthouse Apartment',
    body: 'Top floor with city views and modern finishes.',
    price: 2400,
    location: 'Minneapolis, MN',
    imageUrl: 'https://placehold.co/400x200?text=Penthouse',
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1500,
    verified: true,
    status: 'available',
    isRental: true,
  },
  {
    id: 13,
    userId: 109,
    title: 'Studio Apartment for Rent',
    body: 'Compact and affordable studio ideal for single professionals.',
    price: 950,
    location: 'Fargo, ND',
    imageUrl: 'https://placehold.co/400x200?text=Studio',
    bedrooms: 0,
    bathrooms: 1,
    sqft: 500,
    verified: false,
    status: 'available',
    isRental: true,
  },
  {
    id: 14,
    userId: 109,
    title: 'Suburban Townhome with Garage',
    body: '2-story townhome with modern kitchen and attached garage.',
    price: 1750,
    location: 'West Fargo, ND',
    imageUrl: 'https://placehold.co/400x200?text=Townhome',
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1600,
    verified: false,
    status: 'available',
    isRental: true,
  },
  {
    id: 15,
    userId: 108,
    title: 'Temporary Rental: 2BR Basement Apartment',
    body: 'Available for 6-month lease. Utilities included.',
    price: 1100,
    location: 'Fargo, ND',
    imageUrl: 'https://placehold.co/400x200?text=Basement+Unit',
    bedrooms: 2,
    bathrooms: 1,
    sqft: 900,
    verified: false,
    status: 'available',
    isRental: true,
  },
];
